name: CI
on:
  push:
    branches:
    - master
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install foreman
      uses: Roblox/setup-foreman@v1
      with:
        version: "1.1.0"
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Lint
      run: |
        selene ./out
  style:
    name: Styling
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Style
      uses: JohnnyMorganz/stylua-action@v2.0.0
      with:
        version: "0.17.1"
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --check .