name: Deploy to Production
on:
  push:
    tags:
    - "v*"
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Aftman
      uses: ok-nick/setup-aftman@v0.3.0
      with:
        version: v0.2.7
        token: ${{ github.token }}
    - name: Build place file
      run: rojo build -o game.rbxl
    - name: Publish place
      run: rbxcloud experience publish -f game.rbxl -p 13312129162 -u 4637814426 -t published -a ${{ secrets.API_KEY }}