name: Deploy to Staging
on:
  push:
    branches:
    - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./out
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Aftman
      uses: ok-nick/setup-aftman@v0.3.0
      with:
        version: v0.2.7
        token: ${{ github.token }}
    - name: Build place file
      run: rojo build -o game.rbxl
    - name: Publish place
      run: rbxcloud experience publish -f game.rbxl -p 13312123823 -u 4637812689 -t published -a ${{ secrets.API_KEY }}